const CREATE_BOOK = "CREATE_BOOK";
const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL";

const RETRIEVE_BOOK = "RETRIEVE_BOOK";
const RETRIEVE_BOOK_SUCCESS = "RETRIEVE_BOOK_SUCCESS";
const RETRIEVE_BOOK_FAIL = "RETRIEVE_BOOK_FAIL";

const UPDATE_BOOK = "UPDATE_BOOK";
const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
const UPDATE_BOOK_FAIL = "UPDATE_BOOK_FAIL";

const DELETE_BOOK = "DELETE_BOOK";
const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export {
  CREATE_BOOK,
  CREATE_BOOK_SUCCESS,
  CREATE_BOOK_FAIL,
  RETRIEVE_BOOK,
  RETRIEVE_BOOK_SUCCESS,
  RETRIEVE_BOOK_FAIL,
  UPDATE_BOOK,
  UPDATE_BOOK_SUCCESS,
  UPDATE_BOOK_FAIL,
  DELETE_BOOK,
  DELETE_BOOK_SUCCESS,
  DELETE_BOOK_FAIL,
};
